Install at cmd in startup script and support configuring SSD disk type
related-sciences/gce-github-runner pull request #22
Opened 2022-07-08 10:17 UTC by rishisv

* Flag for choosing boot disk type for creating the VM with SSD storage, defaults to SSD
* Installs the at command in startup script as it is a key dependency

2022-07-29 19:34 UTC, ravwojdyla requested changes
@rishisv sorry for late response, this change looks great but we would need to adjust the TTL change.

2022-07-29 19:34 UTC, ravwojdyla commented on action.sh
> +    echo \"gcloud --quiet compute instances delete ${VM_ID} --zone=${machine_zone}\" | at now + 2 hours
@rishisv can we accept this as a parameter please?

2023-03-24 18:19 UTC, andodet commented
It would be great to have this completed and merged as Ubuntu 22.04 doesn't currently include `at` and it needs to be installed as a separate dependency.

Happy to open a fresher PR (if this one got abandoned) to get it merged.

2023-03-24 18:25 UTC, ravwojdyla commented
@andodet please go ahead, PR are welcome.

2023-03-24 20:46 UTC, ravwojdyla commented
Give #30 this is now obsolete. Closing.

2023-03-24 20:46 UTC, closed without merging